// <auto-generated />
using System;
using DisneyMovies.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DisneyMovies.Infrastructure.Migrations
{
    [DbContext(typeof(DisneyMoviesDbContext))]
    [Migration("20220815014651_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("DisneyMovies.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("History")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Age = 14,
                            History = "is a high school student and freelance hero/vigilante. She is unusual in this in that she not only lacks a secret identity, but also remains on good terms with various law enforcement, government, and military agencies. ",
                            ImgUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qsDNX8DPwWydDn9oUIhe1WcTuUH.jpg",
                            Name = "Kimberly Ann Possible",
                            Weight = 50.0
                        });
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.CharacterMedia", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("CharacterMedia");

                    b.HasData(
                        new
                        {
                            CharacterId = 5,
                            MediaId = 5
                        });
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "",
                            Name = "Christmas"
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "",
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "",
                            Name = "Family"
                        });
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.GenreMedia", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GenreId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("GenreMedia");
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Medias");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationInMinutes = 23L,
                            ImgUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qsDNX8DPwWydDn9oUIhe1WcTuUH.jpg",
                            Rating = 3,
                            Title = "Kim Possible",
                            Type = 1
                        });
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.CharacterMedia", b =>
                {
                    b.HasOne("DisneyMovies.Core.Entities.Character", "Character")
                        .WithMany("CharactersMedias")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisneyMovies.Core.Entities.Media", "Media")
                        .WithMany("CharacterMedias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.GenreMedia", b =>
                {
                    b.HasOne("DisneyMovies.Core.Entities.Genre", "Genre")
                        .WithMany("GenreMedias")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DisneyMovies.Core.Entities.Media", "Media")
                        .WithMany("GenreMedias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.Character", b =>
                {
                    b.Navigation("CharactersMedias");
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.Genre", b =>
                {
                    b.Navigation("GenreMedias");
                });

            modelBuilder.Entity("DisneyMovies.Core.Entities.Media", b =>
                {
                    b.Navigation("CharacterMedias");

                    b.Navigation("GenreMedias");
                });
#pragma warning restore 612, 618
        }
    }
}
